name: Build for pull request

on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: make init

      - name: Run tests
        run: make

      - name: Run build
        run: make build
